name: 'I Only Care About Nix'
description: 'Removes all the crap a GitHub Actions VM has so the most space possible is used by Nix'
branding:
  icon: 'crop'
  color: 'red'
# inputs:
runs:
  using: composite
  steps:
    - name: Check disk usage before cleanup
      shell: bash
      run: |
        sudo df -h
    - name: Start the purge
      shell: bash
      run: ${{ github.action_path }}/the-purge.sh
    - name: Check disk usage after cleanup
      shell: bash
      run: |
        sudo df -h
    - name: Setup BTRFS join
      shell: bash
      run: ${{ github.action_path }}/mountpoint-fusion.sh
    - name: Check disk usage after BTRFS setup
      shell: bash
      run: |
        sudo df -h
